server:
  port: 8080
  address:

spring:
  application:
    name: movie-talk
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: oes
  datasource:
    url: ${JDBC_DATABASE_URL}&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  pageSizeZero: true
  #    reasonable: true
  #    supportMethodsArguments: true
  rowBoundsWithCount: true

# custom defined params
user:
  role: USER
  group: User
  level: 0

jwt:
  secret: changeIt
  expire: 21600
  delay: 60